runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin.*
  script: admin.app
  login: admin
- url: /delete.*
  script: main.app
  login: admin

- url: /login
  static_files: static/login.html
  upload: static/login.html

- url: /.*
  script: main.app

env_variables:
  FIREBASE_PROJECT_ID: 'cw-mungo'
