name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'appengine/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_email: "harry.slatyer@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cw-mungo"
          appdir: "appengine"
          usedocker: true
